export const CHANGE_LOCATION = 'LOCATION/CHANGE_LOCATION'
export const FETCH_WEATHER = 'WEATHER/FETCH_WEATHER'
export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'
